import { describe, it, expect, beforeAll, afterAll } from 'bun:test';
import { randomUUID } from 'node:crypto';
import { createTestUser } from '../helpers/auth-helpers.ts';
import { createApiClient, createServiceClient } from '../helpers/api-helpers.ts';
import { waitFor } from '../helpers/wait-helpers.ts';
import { startServices, type Services } from '../setup/start-services.ts';
import { TestLogger } from '../setup/test-logger.ts';

describe('E2E: Full Organization Flow', () => {
  let api: ReturnType<typeof createApiClient>;
  let service: ReturnType<typeof createServiceClient>;
  let services: Services;
  let logger: TestLogger;
  let userId: string;

  beforeAll(async () => {
    logger = new TestLogger();
    services = await startServices();

    const user = await createTestUser();
    userId = user.userId;
    api = createApiClient(user.accessToken);
    service = createServiceClient();
    await api.createDeviceSession();
  }, 30_000);

  afterAll(() => {
    services?.stop();
    logger?.saveReport('tests/e2e/reports/organization-full.json');
  });

  it('worker-generated candidates appear in candidate list', async () => {
    logger.step('create 3 fragments with shared "blockchain" keyword');
    const fragmentIds: string[] = [];
    for (let i = 0; i < 3; i++) {
      const fid = randomUUID();
      await api.captureFragment({
        fragmentId: fid,
        sourceType: 'text',
        rawTextOptional: `Blockchain technology ${i + 1}: distributed ledger blockchain systems for decentralized blockchain applications`,
        titleOptional: `Blockchain Note ${i + 1}`,
        createdAt: new Date().toISOString(),
      });
      fragmentIds.push(fid);
    }

    logger.step('wait for all fragments to be ready');
    for (const fid of fragmentIds) {
      await waitFor(
        () => service.getFragment(fid),
        (f) => f !== null && f.status === 'ready',
        { timeoutMs: 30_000, label: 'fragment ready' },
      );
    }

    logger.step('verify candidates generated by worker');
    const candidates = await service.getCandidates(userId);
    expect(candidates.length).toBeGreaterThan(0);
    logger.step('found candidates', { count: candidates.length });
  }, 120_000);

  it('confirmed candidate no longer appears in candidate list', async () => {
    const candidates = await service.getCandidates(userId);
    if (candidates.length === 0) {
      logger.step('skip: no candidates to confirm');
      return;
    }

    const objectId = candidates[0].object_id as string;
    logger.step('confirm first candidate', { objectId });
    const result = await api.reviewDerivedObject(objectId, 'confirm');
    expect(result.status).toBe(200);

    logger.step('verify not in candidate list');
    const remaining = await service.getCandidates(userId);
    const found = remaining.find((c) => c.object_id === objectId);
    expect(found).toBeUndefined();
  }, 10_000);

  it('supporting fragment count matches junction table', async () => {
    const objectId = randomUUID();
    const now = new Date().toISOString();

    logger.step('insert test candidate with known fragments');
    await service.insertUser(userId);
    await service.insertDerivedObject({
      object_id: objectId,
      user_id: userId,
      object_type: 'topic',
      status: 'candidate',
      title: 'Count Test Topic',
      summary: 'Testing fragment count.',
      key_entities: [],
      rule_version: 'e2e-test',
      supporting_fragment_count: 2,
      citations: [],
      relation_edges: [],
      created_at: now,
      updated_at: now,
    });

    const obj = await api.getDerivedObject(objectId);
    expect(obj).not.toBeNull();
    expect(Number(obj.supporting_fragment_count)).toBe(2);
  }, 10_000);
});
